### ISSUE TITLE
你好，运行报下面错误，是不是因为gensim版本不一样

### ISSUE THREAD

**Issue by yanqiangmiffy** [Zbored/Chinese-sentiment-analysis#1]
G:\ProgramData\Anaconda3\lib\site-packages\gensim\models\word2vec.py in train(self, sentences, total_examples, total_words, epochs, start_alpha, end_alpha, word_count, queue_factor, report_delay, compute_loss)
    841 
    842         if total_words is None and total_examples is None:
--> 843             raise ValueError("You must specify either total_examples or total_words, for proper alpha and progress calculations. The usual value is total_examples=model.corpus_count.")
    844         if epochs is None:
    845             raise ValueError("You must specify an explict epochs count. The usual value is epochs=model.iter.")

ValueError: You must specify either total_examples or total_words, for proper alpha and progress calculations. The usual value is total_examples=model.corpus_count.

**Comment by brandonchow1997** [comment]
我也报这个错，请问有解决方法吗

**Comment by Yingshiyu** [comment]
> 我也报这个错，请问有解决方法吗
请问您解决这个问题了么

**Comment by yanqiangmiffy** [comment]
> > 我也报这个错，请问有解决方法吗
> > 请问您解决这个问题了么

加上这个total_examples=model.corpus_count参数
